# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SABA\Downloads\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(MainMenu)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setStyleSheet("font-size: 24px; font-weight: bold;")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.startButton = QtWidgets.QPushButton(MainMenu)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.settingsButton = QtWidgets.QPushButton(MainMenu)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout.addWidget(self.settingsButton)
        self.quitButton = QtWidgets.QPushButton(MainMenu)
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout.addWidget(self.quitButton)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("MainMenu", "Minesweeper"))
        self.startButton.setText(_translate("MainMenu", "Start"))
        self.settingsButton.setText(_translate("MainMenu", "Settings"))
        self.quitButton.setText(_translate("MainMenu", "Quit"))
